# Generated by Django 5.2 on 2025-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_eventtype_genre_pricecategory_activities_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
